AskDocta/AskDocta/urls.py
from django.contrib import admin
from django.urls import include,path

urlpatterns = [
    # path('admin/', admin.site.urls),
    path('', include('api.urls'))
]

AskDocta/api/urls.py
from django.conf.urls import url, include
from django.urls import path
from api.models import Profile
from rest_framework import routers, serializers, viewsets
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from django.conf import settings

from . import views

# Serializers define the API representation.
# class RequestSerializer(serializers.HyperlinkedModelSerializer):
#     class Meta:
#         model = Request
#         fields = ('name', 'message', 'created_at')

# class DoctorSerializer(serializers.HyperlinkedModelSerializer):
#     class Meta:
#         model = Doctor
#         fields = ('first_name', 'last_name', 'specialty', 'gender')

# # ViewSets define the view behavior.
# class RequestViewSet(viewsets.ModelViewSet):
#     queryset = Request.objects.all()
#     serializer_class = RequestSerializer

# class DoctorViewSet(viewsets.ModelViewSet):
#     queryset = Doctor.objects.all()
#     serializer_class = DoctorSerializer

# # Routers provide an easy way of automatically determining the URL conf.
# router = routers.DefaultRouter()
# router.register(r'requests', RequestViewSet)
# router.register(r'doctors', DoctorViewSet)

# Wire up our API using automatic URL routing.
# Additionally, we include login URLs for the browsable API.
urlpatterns = [
    # url(r'^', include(router.urls)),
    # url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    path('sms', views.sms, name='sms'),
    path('patient/new', views.new_patient, name='patient'),
    path('patient', views.patient, name='patient'),
    path('management', views.profiles, name='profiles'),
    path('management/<int:request_id>', views.profiles_details, name='profiles_details'),
    path('doctor/patients/<int:request_id>', views.doctor_patients_detail, name='doctor_patients_detail'),
    path('doctor/patients', views.doctor_patients, name='doctor_patients'),
    path('', views.index, name='index'),
    path('profile/edit', views.update_profile, name='edit'),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('request/<int:request_id>', views.detail, name='detail'),
    url(r'^password_reset/$', auth_views.PasswordResetView.as_view(), name='password_reset'),
    url(r'^password_reset/done/$', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    url(r'^reset/done/$', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
]


AskDocta/api/models.py
from django.db import models
from phonenumber_field.modelfields import PhoneNumberField
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from django import forms
from multiselectfield import MultiSelectField

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    specialty = models.CharField(max_length=50)
    gender = models.CharField(max_length=30)
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    is_doctor = models.BooleanField(default=False)
    is_registrar = models.BooleanField(default=False)
    is_admin = models.BooleanField(default=False)
    phone = PhoneNumberField(blank=True, help_text="(include country code)")

class Request(models.Model):
    message = models.TextField();
    phonenumber = models.BigIntegerField();
    created_at = models.DateTimeField(auto_now_add=True);

    def __str__(self):
        "Returns Name and "
        return '%s %s' % (self.first_name, self.last_name)

class Patient(models.Model):
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    height = models.FloatField(max_length=30)
    weight = models.FloatField(max_length=30)
    DOB = models.DateField();
    GENDER_CHOICES = (('M', 'Male'), ('F', 'Female'))
    sex = models.CharField(max_length=1, choices=GENDER_CHOICES);
    ISSUE_CHOICES = (
        (1,'Blood'), (2, 'Cancer'),(3, 'Cardiovascular/Heart'),(4, 'Ear'),(5, 'Eye'),(6, 'Infection'),(7, 'Immune'),(8, 'Injury/Accident'),
        (9, 'Mental Health'),(10, 'Metabolic/Endocrine'),(11, 'Muscle/Bone'),(12, 'Neurological'),(13, 'Oral and gastrointestinal'),
        (14, 'Renal and Urogenital'),(15, 'Reproduction/Childbirth'),(16, 'Respiratory'),(17, 'Skin'),(18, 'Stroke'),(19, 'General/Other')
    )
    issue = models.IntegerField(choices=ISSUE_CHOICES);
    issue_description = models.CharField(max_length=255)
    other_issue = models.CharField(max_length=255);
    start = models.DateField(blank=True, null=True);
    start_details = models.CharField(max_length=255);
    PAIN_CHOICES = ((1,'Low'), (2, 'Medium'),(3, 'High'))
    severity = models.IntegerField(choices=PAIN_CHOICES);
    ALLERGY_CHOICES = (('N', 'None'),('L', 'Latex'),('P', 'Penicillin'),('A', 'Aspirin'),('I', 'Iodine'),('S', 'Shellfish'),('O', 'Other'))
    MED_HIST_CHOICES = (
        ('none', 'None'),
        ('bleed', 'Bleeding Problems'),
        ('anemia', 'Anemia'),
        ('hbp', 'High blood pressure'),
        ('hd', 'Heart disease/heart attack'),
        ('af', 'Atrial Fibrillation'),
        ('pace', 'Pacemaker'),
        ('lung', 'Lung Disease'),
        ('copd', 'COPD/emphysema'),
        ('kd', 'Kidney disease'),
        ('liv', 'Liver disease'),
        ('hep', 'Hepatitis'),
        ('col', 'Colitis'),
        ('div', 'Diverticulitis'),
        ('ulc', 'Ulcers/GERD'),
        ('thy', 'Thyroid problems'),
        ('lup', 'Lupus'),
        ('arth', 'Arthritis'),
        ('gout', 'Gout'),
        ('park', 'Parkinson\'s'),
        ('stroke', 'Stroke/TIA'),
        ('seiz', 'Seizures'),
        ('DVT', 'Phlebitis/DVT (blood clot)'),
        ('ven', 'Venereal disease'),
        ('canc', 'Cancer'),
        ('asth', 'Asthma'),
        ('diab', 'Diabetes'),
        ('hiv', 'HIV or AIDS'),
        ('hc', 'High Cholesterol')
    )
    FAM_HIST_CHOICES = (
        ('none', 'None'),
        ('hbp', 'High blood pressure'),
        ('hd', 'Heart disease/heart attack'),
        ('diab', 'Diabetes'),
        ('arth', 'Arthritis')
    )
    allergies = MultiSelectField(choices=ALLERGY_CHOICES);
    med_hist = MultiSelectField(choices=MED_HIST_CHOICES);
    fam_hist = MultiSelectField(choices=FAM_HIST_CHOICES);
    other_allergy = models.CharField(max_length=255)
    curr_meds = models.CharField(max_length=255);
    other_hist = models.CharField(max_length=255);
    other_fam_hist = models.CharField(max_length=255);
    SMOKE_OPT = (('N', 'None'),('F', 'Former'),('S', 'Some Days'),('M', 'Most/Every Day'))
    smoke = models.CharField(max_length=1, choices=SMOKE_OPT);
    ALC_OPT = (('N', 'None'),('O', 'Occasional'),('F', 'Frequent'))
    alc = models.CharField(max_length=1, choices=ALC_OPT);
    registrar = models.ForeignKey(Profile, on_delete=models.PROTECT, related_name='registrar', blank=True,
        null=True);
    doctor = models.ForeignKey(Profile, on_delete=models.PROTECT, related_name='doctor', blank=True,
        null=True);
    created_at = models.DateTimeField(auto_now_add=True);

    def __str__(self):
        "Returns Name and "
        return '%s %s' % (self.first_name, self.last_name)

# class Poll(models.model):
#     s3_link = models.CharField(max_length=255)
#     created_at = models.DateTimeField(auto_now_add=True);

@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)

@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()

    

AskDocta/api/forms.py
from django import forms
from api.models import User, Patient, Profile
import datetime
from multiselectfield import MultiSelectField

class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('email',)

class ProfileRoleForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('is_doctor', 'is_registrar')

class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('first_name', 'last_name', 'phone')

class PermissionsForm(forms.ModelForm):
    PERMISSION_CHOICES = (('0', 'No'), ('1', 'Yes'))
    # is_registrar = forms.CharField(max_length=1, choices=PERMISSION_CHOICES);
    # is_doctor = forms.CharField(max_length=1, choices=PERMISSION_CHOICES);
    
    class Meta:
        model = Profile
        fields = ('is_registrar', 'is_doctor')

ISSUE_CHOICES = (
        (1,'Blood'), (2, 'Cancer'),(3, 'Cardiovascular/Heart'),(4, 'Ear'),(5, 'Eye'),(6, 'Infection'),(7, 'Immune'),(8, 'Injury/Accident'),
        (9, 'Mental Health'),(10, 'Metabolic/Endocrine'),(11, 'Muscle/Bone'),(12, 'Neurological'),(13, 'Oral and gastrointestinal'),
        (14, 'Renal and Urogenital'),(15, 'Reproduction/Childbirth'),(16, 'Respiratory'),(17, 'Skin'),(18, 'Stroke'),(19, 'General/Other')
    )

class SortForm(forms.Form):
    issue= forms.CharField(widget=forms.Select(choices=ISSUE_CHOICES))


class PatientForm(forms.ModelForm):
    start_int = 1900
    today = datetime.datetime.now()
    current_year = today.year
    year_choices =[]
    while start_int <= current_year:
        year_choices.append(start_int)
        start_int +=1
    DOB = forms.DateField(widget=forms.SelectDateWidget(years=year_choices))
    start = forms.DateField(required=False, widget=forms.SelectDateWidget(years=year_choices))
    start_details = forms.CharField(required=False)
    other_issue = forms.CharField(required=False)
    issue_description = forms.CharField(required=False)
    other_allergy = forms.CharField(required=False)
    curr_meds = forms.CharField(required=False)
    other_hist = forms.CharField(required=False)
    other_fam_hist = forms.CharField(required=False)

    class Meta:
        model = Patient
        fields = (
            'first_name',
            'last_name',
            'height',
            'weight',
            'DOB',
            'sex',
            'issue',
            'issue_description',
            'other_issue',
            'start',
            'severity',
            'allergies',
            'other_allergy',
            'curr_meds',
            'med_hist',
            'other_hist',
            'fam_hist',
            'other_fam_hist',
            'smoke',
            'alc',
            'registrar'
        )

AskDocta/api/templates/patient/index.html
{% extends "base.html" %}

{% block content %}
<div class="py-5">
    <div class="container">
    <h2>Sorting:</h2>
    <a class="btn btn-light" href="?order_by=severity&direction=desc" role="button">Severity ↓</a>
    <a class="btn btn-light" href="?order_by=severity&direction=asc" role="button">Severity ↑</a>
    <a class="btn btn-light" href="?order_by=created_at&direction=desc" role="button">Created ↓</a>
    <a class="btn btn-light" href="?order_by=created_at&direction=asc" role="button">Created ↑</a>
    <a class="btn btn-light" href="?order_by=start&direction=desc" role="button">Start ↓</a>
    <a class="btn btn-light" href="?order_by=start&direction=asc" role="button">Start ↑</a>
    <br>
    <br>
    <form method="post">
        {% csrf_token %}{{ sort_form.issue.errors }} 
          <label for="{{ sort_form.issue.id_for_label }}">Issue:</label>
          {{ sort_form.issue }} 
      <button class="btn btn-light" type="submit">Sort</button>
    </form>
    <br>
    <h1>Requests:</h1>
    {% if patients %}
        {% for p in patients %}
          <div class="row py-2 border-top bordert-bottom border-light">
            <div class="col-md-8">
              <div class="row">
                <div class="col-md-6">
                  <h6 class=""><b class="font-weight-bold">Name:</b> {{ p.first_name }} {{ p.last_name }}</h6>
                </div>
                <div class="col-md-6">
                  <h6><b class="font-weight-bold">Sex</b> {{ p.sex }}</h6>
                </div>
              </div>
              <div class="row">
                <div class="col-md-6">
                  <h6 class=""><b class="font-weight-bold">Current Issue:</b> {{ issue_dict|get_item:p.issue }} {% if p.other_issue %}| Details: {{ p.other_issue }}{% endif %}</h6>
                </div>
                <div class="col-md-6">
                  <h6><b class="font-weight-bold">Severity:</b> 
                  {% if p.severity == 1%}
                  Low
                  {% elif p.severity == 2%}
                  Medium
                  {% elif p.severity == 3%}
                  High
                  {% endif %}</h6>
                </div>
              </div>
              <div class="row">
                <div class="col-md-12">
                {% if p.issue_description %}
                <h6 class=""><b class="font-weight-bold">Further Details:</b> {{ p.issue_description }}</h6>
                {% endif %}
                </div>
              </div>
              <div class="row">
                <div class="col-md-12">
                {% if p.start %}
                <h6 class=""><b class="font-weight-bold">Start of Issue:</b> {{ p.start }}</h6>
                {% endif %}
                {% if p.start_details %}
                <h6 class=""><b class="font-weight-bold">Start of Issue:</b> {{ p.start_deatils }}</h6>
                {% endif %}
                </div>
              </div>
              <div class="row">
                <div class="col-md-6">
                  <h6 class=""><b class="font-weight-bold">Height:</b> {{ p.height }} cm</h6>
                </div>
                <div class="col-md-6">
                  <h6><b class="font-weight-bold">Weight</b> {{ p.weight }} kg</h6>
                </div>
              </div>
              <div class="row">
                <div class="col-md-12">
                  <h6 class=""><b class="font-weight-bold">Allergies:</b> {{ p.allergies }}
                    {% if p.other_allergy %}
                    , {{ p.other_allergy }}
                    {% endif %}
                  </h6>
                  {% if p.curr_meds %}
                  <h6 class=""><b class="font-weight-bold">Current Medications:</b> {{ p.curr_meds }}</h6>
                  {% endif %}
                  {% if p.med_hist %}
                  <h6 class=""><b class="font-weight-bold">Medical History:</b> {{ p.med_hist }}</h6>
                  {% endif %}
                  {% if p.other_hist %}
                  <h6 class=""><b class="font-weight-bold">Other History:</b> {{ p.other_hist }}</h6>
                  {% endif %}
                  {% if p.fam_hist %}
                  <h6 class=""><b class="font-weight-bold">Family History:</b> {{ p.fam_hist }}</h6>
                  {% endif %}
                  <div class="row">
                    <div class="col-md-6">
                      <h6 class=""><b class="font-weight-bold">Smoke:</b>
                        {% if p.smoke == "N"%}
                        None
                        {% elif p.smoke == "F"%}
                        Former
                        {% elif p.smoke == "S"%}
                        Some Days
                        {% else %}
                        Most/Every Day
                        {% endif %}
                      </h6>
                    </div>
                    <div class="col-md-6">
                      <h6 class=""><b class="font-weight-bold">Alcohol:</b> 
                        {% if p.alc == "N"%}
                        None
                        {% elif p.alc == "O"%}
                        Occasional
                        {% else %}
                        Frequent
                        {% endif %}
                      </h6>
                    </div>
                  </div>
                  <h6 class=""><b class="font-weight-bold">Request Created:</b> {{ p.created_at }}</h6>
              </div>
            </div>
          </div>
            <div class="col-md-4">
                <form action="/request/{{p.id}}" method="post">
                    {% csrf_token %}
                    <input type="hidden" name="grab" value="1">
                    <button type="submit" class="btn btn-lg btn-block btn-secondary">Accept Request</button>
                </form>
            </div> 
          </div>
        {% endfor %}
    {% else %}
        <h4>There are no outstanding requests.</h4>
    {% endif %}
    </div>
</div>        
{% endblock content %}

AskDocta/api/templates/patient/new.html
{% extends "base.html" %}

{% block content %}
<div class="py-5" style="">
	<div class="container">
	  <div class="row justify-content-center">
	    <div class="p-5 col-lg-12">
	    	<h1>New Patient:</h1>
	    	<br>
	    	<h6 class="font-weight-bold"><b class="text-danger">*</b> Indicates a required field</h6>
	    	<br>
			<form method="post">
				{% csrf_token %}
				{{ patient_form.non_field_errors }}
				<div class="row" class="font-weight-bold">
					<div class="col-lg-6 col-sm-12">
						<p>{{ patient_form.first_name.errors }} 
							<label class="font-weight-bold" for="{{ patient_form.first_name.id_for_label }}">First Name:</label>
							<b class="text-danger font-weight-bold">*</b>
							{{ patient_form.first_name }} 
						</p>
					</div>
					<div class="col-lg-6 col-sm-12">
						<p>{{ patient_form.last_name.errors }} 
							<label class="font-weight-bold" for="{{ patient_form.last_name.id_for_label }}">Last Name:</label>
							<b class="text-danger font-weight-bold">*</b>
							{{ patient_form.last_name }} 
						</p>
					</div>
				</div>
				<div class="row">
					<div class="col-lg-6 col-sm-12">
						<p>{{ patient_form.height.errors }} 
							<label class="font-weight-bold" for="{{ patient_form.height.id_for_label }}">Height (in cm):</label>
							<b class="text-danger font-weight-bold">*</b>							
							{{ patient_form.height }} 
						</p>
					</div>
					<div class="col-lg-6 col-sm-12">
						<p>{{ patient_form.weight.errors }} 
							<label class="font-weight-bold" for="{{ patient_form.weight.id_for_label }}">Weight (in kg):</label>
							<b class="text-danger font-weight-bold">*</b>
							{{ patient_form.weight }} 
						</p>
					</div>
				</div>
				<div class="row">
					<div class="col-lg-6 col-sm-12">
						<p>{{ patient_form.DOB.errors }} 
							<label class="font-weight-bold" for="{{ patient_form.DOB.id_for_label }}">Date of Birth:</label>
							<b class="text-danger font-weight-bold">*</b>
							{{ patient_form.DOB }} 
						</p>
					</div>
					<div class="col-lg-6 col-sm-12">
						<p>{{ patient_form.sex.errors }} 
							<label class="font-weight-bold" for="{{ patient_form.sex.id_for_label }}">Sex:</label>
							<b class="text-danger font-weight-bold">*</b>
							{{ patient_form.sex }} 
						</p>
					</div>
				</div>
				<p>{{ patient_form.issue.errors }} 
					<label class="font-weight-bold" for="{{ patient_form.issue.id_for_label }}">Issue:</label>
					<b class="text-danger font-weight-bold">*</b>
					{{ patient_form.issue }} 
				</p>
				<p>
				    {{ patient_form.other_issue.errors }}<label class="font-weight-bold" for="{{ patient_form.other_issue.id_for_label }}">Explain if 'General/Other':</label>
				    {{ patient_form.other_issue }}
				</p>
				<p>
				    {{ patient_form.issue_description.errors }}<label class="font-weight-bold" for="{{ patient_form.issue_description.id_for_label }}">Describe your current issue:</label>
				    {{ patient_form.issue_description }}
				</p>
				<p>{{ patient_form.start.errors }} 
				    <label class="font-weight-bold" for="{{ patient_form.start.id_for_label }}">When did the issue start?:</label>
				    {{ patient_form.start }} 
				</p>
				<p>
				    {{ patient_form.start_details.errors }}<label class="font-weight-bold" for="{{ patient_form.start_details.id_for_label }}">Or in general terms (Such as "Two weeks ago"):</label>
				    {{ patient_form.start_details }}
				</p>
				<p>
				    {{ patient_form.severity.errors }}<label class="font-weight-bold" for="{{ patient_form.severity.id_for_label }}">How severe is your pain?:</label>
					<b class="text-danger font-weight-bold">*</b>
				    {{ patient_form.severity }}
				</p>
				<p>
				    {{ patient_form.allergies.errors }}<label class="font-weight-bold" for="{{ patient_form.allergies.id_for_label }}">Tick any allergies you have:</label>
					<b class="text-danger font-weight-bold">*</b>
				    <div class="row">
				    {% for value, text in patient_form.allergies.field.choices %}
					  <div class="ui slider checkbox col-lg-3 col-sm-12">
					    <input id="id_allergies_{{ forloop.counter0 }}" name="{{ patient_form.allergies.name }}" type="checkbox" value="{{ value }}"{% if value in checked_providers %} checked="checked"{% endif %}>
					    <label>{{ text }}</label>
					  </div>
					{% endfor %}
					</div>
				</p>
				<p>
				    {{ patient_form.other_allergy.errors }}<label class="font-weight-bold" for="{{ patient_form.other_allergy.id_for_label }}">List any other allergies not above:</label>
				    {{ patient_form.other_allergy }}
				</p>
				<p>
				    {{ patient_form.med_hist.errors }}<label class="font-weight-bold" for="{{ patient_form.med_hist.id_for_label }}">Tick any applicable personal medical histories:</label>
					<b class="text-danger font-weight-bold">*</b>
				    <div class="row">
				    {% for value, text in patient_form.med_hist.field.choices %}
					  <div class="ui slider checkbox col-lg-3 col-sm-12">
					    <input id="id_med_hist_{{ forloop.counter0 }}" name="{{ patient_form.med_hist.name }}" type="checkbox" value="{{ value }}"{% if value in checked_providers %} checked="checked"{% endif %}>
					    <label>{{ text }}</label>
					  </div>
					{% endfor %}
					</div>
				</p>
				<p>
				    {{ patient_form.other_hist.errors }}<label class="font-weight-bold" for="{{ patient_form.other_hist.id_for_label }}">List any other personal medical history not above:</label>
				    {{ patient_form.other_hist }}
				</p>
				<p>
				    {{ patient_form.fam_hist.errors }}<label class="font-weight-bold" for="{{ patient_form.fam_hist.id_for_label }}">Tick any applicable family medical histories:</label>
					<b class="text-danger font-weight-bold">*</b>
				    <div class="row">
				    {% for value, text in patient_form.fam_hist.field.choices %}
					  <div class="ui slider checkbox col-lg-3 col-sm-12">
					    <input id="id_fam_hist_{{ forloop.counter0 }}" name="{{ patient_form.fam_hist.name }}" type="checkbox" value="{{ value }}"{% if value in checked_providers %} checked="checked"{% endif %}>
					    <label>{{ text }}</label>
					  </div>
					{% endfor %}
					</div>
				</p>
				<p>
				    {{ patient_form.other_fam_hist.errors }}<label class="font-weight-bold" for="{{ patient_form.other_fam_hist.id_for_label }}">List any other family medical history not above:</label>
				    {{ patient_form.other_fam_hist }}
				</p>
				<p>
				    {{ patient_form.smoke.errors }}<label class="font-weight-bold" for="{{ patient_form.smoke.id_for_label }}">How frequently do you smoke?:</label>
					<b class="text-danger font-weight-bold">*</b>
				    {{ patient_form.smoke }}
				</p>
				<p>
				    {{ patient_form.alc.errors }}<label class="font-weight-bold" for="{{ patient_form.alc.id_for_label }}">How frequently do you drink?:</label>
					<b class="text-danger font-weight-bold">*</b>
				    {{ patient_form.alc }}
				</p>
				<input type="hidden" name="registrar" id="id_registrar" value="{{registrar}}">
				<button type="submit">Save changes</button>
			</form>
		</div>
      </div>
    </div>
  </div>
{% endblock content %}